### ISSUE TITLE
CONNECTION REFUSED when converting

### ISSUE THREAD

**Issue by jmcollin78** [pofider/phantom-html-to-pdf#1]
Hello,

I've trid your solution and I issue this error when trying your sample code:

<pre>[2015-03-31 08:21:33.153] [ERROR] cld-apps.services.invoices - Could not generate invoice pdf cause "{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }"
</pre>

Any clues of what happens ?

My piece of code:
```js
var conversion = require('phantom-html-to-pdf')({
        numberOfWorkers: 2,
        timeout: 5000,
        tmpDir: '../temp'
    });

exports.downloadInvoice = function (req, res, next) {
    log.info('Downloading invoice "%s (%s)"', req.invoice._id, req.invoice.number);
    conversion({ html: '<h1>Hello World</h1>' }, function(err, pdf) {
        if (err) {
            log.error('Could not generate invoice pdf cause "%s"', util.inspect(err));
            return next(new jmcnetException.TechnicalException(err));
        }
        log.debug('pdf is "%s"', util.inspect(pdf));
        pdf.stream.pipe(res);
        
    });
};
```

**Comment by pofider** [comment]
Hi, just tried your piece of code with express and works for me on windows and ubuntu as well.

- Aren't you working on some kind of a shared hosting environment?
- does `../temp` exist?

**Comment by jmcollin78** [comment]
Hi,
I'm working on a local Windows PC,
../temp exists. If I remove it, I've got another error.

Is there something to run before launching tests ? A phantomJS server or something like that ?

JM.

**Comment by jmcollin78** [comment]
HUm I've got another error now maybe more explicit to you:
"{ [Error: Timeout] weak: true, message: 'Timeout' }" is returned by conversion into err object.
Does this make sense for you ?

JM.

**Comment by jmcollin78** [comment]
Hum I notice that this error appears only on the first call. Subsequent call are OK. Maybe it is due to start time or start time synchro (my PC is relatively slow).

JM.

**Comment by pofider** [comment]
Oh, that is the problem probably. It is waiting just 500ms for phantomjs.exe to start what could be not enough for slower computer.

I will think about smarter implementation here.

**Comment by jmcollin78** [comment]
OK. Maybe you van tell me where is this  timeout set. I will change
manually waiting for your smarter implémentation.

**Comment by pofider** [comment]
I think it should be here
https://github.com/pofider/phantom-workers/blob/master/lib/phantomWorker.js#L42

**Comment by pofider** [comment]
Now it is fixed in the dependent package.
https://github.com/pofider/phantom-workers/releases/tag/0.1.2

**Comment by 0x62** [comment]
I'm having exactly this error at the moment, running on a 2015 Macbook Pro.

```
{ Error: connect ECONNREFUSED 127.0.0.1:54363
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 54363 }
```

Code:

```
const phantomExport = require('phantom-html-to-pdf')();

phantomExport({ html: "<h3>Hello world</h3>" }, (err, pdf) => {
  console.log(err);
})
```

```
$ node -v
v6.9.0
```

**Comment by pofider** [comment]
@0x62 Do you have macOS Sierra?

The default phantomjs doesn't work there and you need to use phantomjs2
https://github.com/pofider/phantom-html-to-pdf#phantomjs2

**Comment by 0x62** [comment]
I am on Sierra. Thank's for the heads up.

**Comment by chevin99** [comment]
@pofider it would be helpful to mention in the readme/docs that phantomjs2 is required on macOS Sierra.  Thankfully searching around and finding this issue helped me figure that out, but I imagine others may be having the same problem when trying to run the 'hello world' example.  Thanks for your work on this 😄.

**Comment by pofider** [comment]
@chevin99 I've updated readme to mentioned this. Don't hesitate to send PR next time :)

**Comment by mcrowder65** [comment]
I am on macOS Sierra and I get this error occasionally, and I am also using phantomjs2.

**Comment by juergengunz** [comment]
@mcrowder65  same for me, did you end up fixing that?
