### ISSUE TITLE
Can't set footer

### ISSUE THREAD

**Issue by PaddyMann** [pofider/phantom-html-to-pdf#10]
We need to set the content of the footer as part of the paperSize call (in order to add page numbering), so I want to be able to set up the config below.

```
  paperSize: {
    format: 'A4',
    orientation: 'portrait',
    footer: {
      height: '1cm',
      // Pass as a string to overcome a limitation of node-phantom
      // See description here: http://stackoverflow.com/questions/17102287/footers-contents-dont-seem-to-work
      contents: 'function(pageNum, numPages) { if(pageNum > 1) { return \'<div style="text-align: center;font-family:Arial;font-size:12px;color:#333">\' + pageNum + \'</div>\'; } }'
    },
    margin: {
      top: '2cm',
      left: '2cm',
      right: '2cm',
      bottom: '1cm'
    }
  },
```

Unfortunately, it seems there's no support for `footer`. I'm going to take a look under the hood now to see if I can suggest a solution :)

**Comment by pofider** [comment]
Use {#pageNum} and {#numPages} as placeholders for the current page number and total number of pages inside footer property. 

```js
conversion({
    html: "<h1>Hello world</h1>",
    header: "{#pageNum}/{#numPages} ",
}
```

It needs to be documented. Please keep this open.

**Comment by PaddyMann** [comment]
Thanks - that works :)

Can it be styled and positioned? (if not, I'll need to find an alternative workaround)
