### ISSUE TITLE
PDF image not shown and format issue

### ISSUE THREAD

**Issue by karthikn2510** [pofider/phantom-html-to-pdf#101]
Hi I am using phantom-html-to-pdf v 0.5.6, the image is not shown and also facing format issue. I attached a screenshot for your reference.

![travelerissue](https://user-images.githubusercontent.com/18029596/48115845-3194ce00-e28a-11e8-9a5e-458b9b2d7b4b.png)

**Comment by pofider** [comment]
Hi,

this package is just a wrapper for phantomjs.
We can't solve the rendering issues of phantomjs here.

You can try luck in the phantomjs repository to get some help.
