### ISSUE TITLE
img src=""

### ISSUE THREAD

**Issue by stellanhaglund** [pofider/phantom-html-to-pdf#17]
I have some stuff that needs to fetch images dynamically, is there any way to wait until it all is rendered before printing?

**Comment by pofider** [comment]
This would help?
https://github.com/pofider/phantom-html-to-pdf#programmatic-pdf-printing

**Comment by IonicaBizau** [comment]
I also replied here: https://github.com/IonicaBizau/nodeice/issues/11#issuecomment-163232839

Maybe it helps someone in the future. :smile:

**Comment by stellanhaglund** [comment]
If there where images in your task rows of your example and the task rows
was dynamic where would you place the onload script?

:)

Sorry for all the questions! ;)

onsdag 9 december 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by bjrmatos** [comment]
seeing the referenced issue i think this is solved.. re-open if not :)
