### ISSUE TITLE
pick up console logs

### ISSUE THREAD

**Issue by stellanhaglund** [pofider/phantom-html-to-pdf#18]
I'm running the package in a heroku dyno and I'm trying to find a way to get logs from the template picked up by phantom and shown in my heroku console, 

I tried adding this to the serverScript.js 

page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

but that didn't work.. 

I haven't worked with phantom at all before.

**Comment by bjrmatos** [comment]
@stellanhaglund what `strategy` are you using? `phantom-server` or `dedicated-process`?

**Comment by stellanhaglund** [comment]
phantom-server

2015-12-10 20:32 GMT+01:00 BJR Matos <notifications@github.com>:

**Comment by bjrmatos** [comment]
ok, let me try it on my PC when i comeback home

**Comment by bjrmatos** [comment]
it works for me..

<img width="1001" alt="captura de pantalla 2015-12-10 a las 11 55 32 p m" src="https://cloud.githubusercontent.com/assets/4262050/11736240/90c97024-9f99-11e5-956d-6a0805b77a33.png">

**Comment by bjrmatos** [comment]
i'm closing this because i don't think it is something that we can support for both strategies (`dedicated-process` and `phantom-server`).

**Comment by bjrmatos** [comment]
however, if you find a way to make it work for both strategies send a PR

**Comment by stellanhaglund** [comment]
Ok, im using mustache for the html and its in a separete file, could that
make any difference?

fredag 11 december 2015 skrev BJR Matos <notifications@github.com>:

**Comment by bjrmatos** [comment]
not really, it should work..

if you can create a repository with the code you are trying, i can help you more quickly

**Comment by stellanhaglund** [comment]
Just a little info..

When I run the app locally it shows just like in your example, but for some reason it doesn't in heroku.

That could be good to know, if you know a reason why I would be happy to hear about it! 

Thanks for your help! :)
