### ISSUE TITLE
Can't we set password protection?

### ISSUE THREAD

**Issue by ghost** [pofider/phantom-html-to-pdf#28]
I want to use this module for creating pdf file. but with a functionality of password protection. can we do that using this module?? or not?

**Comment by bjrmatos** [comment]
sorry, this is not possible.. phantomjs doesn't provide a way to protect a pdf file with a password

**Comment by pofider** [comment]
Adding password protection is not a concern of this package. Please try to use additional package and add password encryption to the produced pdf afterwards.

Maybe this would help
https://github.com/nrhirani/node-qpdf
