### ISSUE TITLE
Openshift issue

### ISSUE THREAD

**Issue by jchapelle** [pofider/phantom-html-to-pdf#30]
Hello,

Your library works perfectly locally but when used in openshift, I encounter trouble.

I receive this error. Do you know why ? Is it possible to configure your package to use specific ports ?

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
```

I've read this interresting article in which they say that phantom generates a little local server bind to localhost. Openshift does not allow that. 

I was wondering if there is a way to initialiez your package with another variable that localhost ?

http://stackoverflow.com/questions/32260650/create-a-pdf-from-html-and-send-it-to-the-user-from-a-buffer/34039207

I have tried initializing the library using this : 
```
var conversion = require("phantom-html-to-pdf")({
  host: process.env.OPENSHIFT_NODEJS_IP,
  phantomPath: require('path').dirname(process.env.PHANTOMJS_EXECUTABLE) + '/'
});
```

But his does not work.

Using the library with this :
```
 var conversion = require("phantom-html-to-pdf")({
    strategy: "dedicated-process"
});
```
Is working locally but not in openshift.
In openshift, I receive a "failed to load pdf error" from my browser but no error server side ...

**Comment by pofider** [comment]
Hi,

please try this:

```js
var servHost = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';

var conversion = require("phantom-html-to-pdf")({
    host: servHost,
    portLeftBoundary: 15000,
    portRightBoundary: 35530
});
```

OpenShift allows to start phantomjs server only in specific port range. That is exactly why we have these options.

**Comment by jchapelle** [comment]
I've tried. Locally it works.

In openshift however, I'm still having trouble. No data come in the callback of the conversion call ...
```
conversion(
            {
                html: html,
                paperSize: {
                    format: 'A4',
                    orientation: 'portrait',
                    margin: '1cm'
                }
            },
            function(err, pdf) {

                if (err){
                    console.log(err);
                    def.reject();
               }
                else{
                def.resolve( pdf.stream );
                });
```

```
/var/lib/openshift/56a5028b2d52716b390000e2/app-root/runtime/repo/website/tools/utils.js:79
                def.resolve( pdf.stream );
                                ^
TypeError: Cannot read property 'stream' of undefined

```

**Comment by pofider** [comment]
This works for me as the first try....

```js
var server_port = process.env.OPENSHIFT_NODEJS_PORT || 8080
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1'
 
var http = require('http');
 
var server = http.createServer(function(req, res) {    
    var conversion = require("phantom-html-to-pdf")({ strategy: "dedicated-process"});
    conversion({ html: "<h1>Hello World</h1>" }, function(err, pdf) {        
        res.setHeader('Content-Type', 'application/pdf');
        pdf.stream.pipe(res);
    }); 
});

server.listen(server_port, server_ip_address, function () {
  console.log( "Listening on " + server_ip_address + ", server_port " + server_port)
});
```

**Comment by pofider** [comment]
And with server strategy also

```js
var server_port = process.env.OPENSHIFT_NODEJS_PORT || 8080
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1'
 
var http = require('http');
 
var server = http.createServer(function(req, res) {    
    var conversion = require("phantom-html-to-pdf")({ 
        host: server_ip_address,
        portLeftBoundary: 15000,
        portRightBoundary: 35530 });
    conversion({ html: "<h1>Hello World</h1>" }, function(err, pdf) {        
        res.setHeader('Content-Type', 'application/pdf');
        pdf.stream.pipe(res);
    }); 
});

server.listen(server_port, server_ip_address, function () {
  console.log( "Listening on " + server_ip_address + ", server_port " + server_port)
});
```

**Comment by pofider** [comment]
http://test-pofider.rhcloud.com/

**Comment by jchapelle** [comment]
Well, I just don't get it. My code is the same as yours and it works
locally ...

Seems that openshift is still blocking something ...



On Tue, May 3, 2016 at 2:02 PM, Jan Blaha <notifications@github.com> wrote:

> http://test-pofider.rhcloud.com/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pofider/phantom-html-to-pdf/issues/30#issuecomment-216507633>
>



-- 
Jean Chapelle

**Comment by pofider** [comment]
You should probably try to start over from the scratch.

I've created just plain nodejs-0.10 application and added the mentioned code to the server.js

**Comment by jchapelle** [comment]
Ok, I've found the problem.
The problem came from an image url inside my html that wasn't properly
resolved.

The strange thing is that an error was generated my your conversion method
but my promise.reject didn't interrupt the flow ...



On Tue, May 3, 2016 at 4:02 PM, Jean Chapelle <jean.chapelle@gmail.com>
wrote:

> Well, I just don't get it. My code is the same as yours and it works
> locally ...
>
> Seems that openshift is still blocking something ...
>
>
>
> On Tue, May 3, 2016 at 2:02 PM, Jan Blaha <notifications@github.com>
> wrote:
>
>> http://test-pofider.rhcloud.com/
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pofider/phantom-html-to-pdf/issues/30#issuecomment-216507633>
>>
>
>
>
> --
> Jean Chapelle
>



-- 
Jean Chapelle

**Comment by pofider** [comment]
I guess we can close this.

**Comment by jchapelle** [comment]
Off course, thanks a lot for your support

On Tue, May 3, 2016 at 4:41 PM, Jan Blaha <notifications@github.com> wrote:

> I guess we can close this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pofider/phantom-html-to-pdf/issues/30#issuecomment-216550455>
>



-- 
Jean Chapelle
