### ISSUE TITLE
Extra spacing between characters while generating pdf on RHEL

### ISSUE THREAD

**Issue by amitchhangani** [pofider/phantom-html-to-pdf#32]
Hi Team,
We are facing issue regarding extra spacing between characters while generating pdf in redhat. When the pdf is generated through MAC/Windows, Every character looks as it is displayed in html. We have already ran the command "yum install fontconfig freetype libfreetype.so.6 libfontconfig.so.1 libstdc++.so.6". 
Please suggest whats wrong with the setup.
Attached is the pdf which was generated.
Thanks.
[HealthReport-1.pdf](https://github.com/pofider/phantom-html-to-pdf/files/388091/HealthReport-1.pdf)

**Comment by pofider** [comment]
Hi, 

I didn't encountered such issue when using phantomjs on RHEL, but you can try your luck on [phantomjs](https://github.com/ariya/phantomjs) repository to which is the problem related.

Maybe you can try docker if you move nowhere.

Sorry, I'm not able to give better help.

**Comment by pofider** [comment]
This is rather issue with phantomjs installation than this repository. Closing.
