### ISSUE TITLE
bad quality images

### ISSUE THREAD

**Issue by DanielEliraz** [pofider/phantom-html-to-pdf#33]
Hello, thanks for the package!
I'm using chart js to create charts in my site, then i'm converting it to base64 and send it to the server for the pdf creating. the quality is much worse than in the site. do you have any idea why?
the pdf:
[204026330_concentration (4).pdf](https://github.com/pofider/phantom-html-to-pdf/files/421461/204026330_concentration.4.pdf)
the site:
![site](https://cloud.githubusercontent.com/assets/10989294/17718484/ebbf6612-641c-11e6-9192-3dee6018cd68.PNG)

**Comment by pofider** [comment]
Sorry for the late response.

You can try to increase the quality of the pdf otput: 

```js
conversion({
    html: "<h1>Hello world</h1>",
   format: {
     quality: '100'
   }
```

However I'm not sure if it actually helps.

Unfortunately, increasing pdf quality is not the concert of this package. This is really rather a wrapper around phantomjs which concern is to reuse worker instances. Not more. If you have issues with pdf output itself, you may need to try the luck in phantomjs repository.
