### ISSUE TITLE
Links aren't clickable

### ISSUE THREAD

**Issue by cmoulliard** [pofider/phantom-html-to-pdf#35]
Here is the code that I'm using to render the HTML file (published here) - https://redhat-microservices.github.io/lab_swarm_forge-keycloak/

```
var conversion = require("phantom-html-to-pdf")();
var fs         = require('fs');

var res = fs.createWriteStream('generated_content/hol.pdf');
var src = fs.readFileSync('/Users/chmoulli/MyProjects/litoria/generated_content/hol.html');

conversion({
      html: src.toString(),
      allowLocalFilesAccess: true,
      format: {
          quality: 100
      }
    }, function(err, pdf) {
    console.log(pdf.logs);
    console.log(pdf.numberOfPages);
    pdf.stream.pipe(res);
});
```

The pdf file generated looks good excepted that the links aren't clickable

![screenshot 2016-08-31 11 23 44](https://cloud.githubusercontent.com/assets/463790/18123357/c44cb47a-6f6d-11e6-8717-91a72b1ecf95.png)
![screenshot 2016-08-31 11 23 31](https://cloud.githubusercontent.com/assets/463790/18123356/c44a6062-6f6d-11e6-9620-d8391076bdc0.png)

**Comment by pofider** [comment]
phantomjs@1.x which is included by default in this package doesn't support clickable links in pdf.

However it is supported in phantomjs@2.x which you can opt in, see [here](https://github.com/pofider/phantom-html-to-pdf#phantomjs2)
