### ISSUE TITLE
Space at the end of PDF is of different color

### ISSUE THREAD

**Issue by anirudhkkw** [pofider/phantom-html-to-pdf#40]
<img width="979" alt="screen shot 2016-10-21 at 7 53 57 pm" src="https://cloud.githubusercontent.com/assets/4277996/19601746/31adb41a-97c8-11e6-90b8-956854547efd.png">

Hi,

The footer in my PDFs are of a different color. Bluish tinge. Any way to solve this?

**Comment by anirudhkkw** [comment]
`conversion({ 
   url: URL, 
   fitToPage: true,
   viewportSize: {
        width: 640
    },
    format: {
        quality: 100
    },
    paperSize: {
    	margin: "0cm"
    },
   phantomPath: require("phantomjs-prebuilt").path
 }, function (err, data){
  res.setHeader('Content-type', 'application/pdf');
 	data.stream.pipe(res);
 })`

These are my current settings

**Comment by pofider** [comment]
Interesting, never seen this.

Which os you have? Did you install libfontconfig if it is linux?
Does it also happen if you turn off fit to page?
Does it also happen if you pass html instead of url?

**Comment by anirudhkkw** [comment]
im on ubuntu 16.04.01 
Yes, I have install libfontconfig.
Yes, it still occurs if I pass false for fitToPage.
I haven't tried the HTML yet. 
Could that be the reason? 
I really need the URL though.

**Comment by pofider** [comment]
I'm just suggesting what to try, I don't know if it actually helps...

You would get better support in [phantomjs](https://github.com/ariya/phantomjs) repository. This package only wraps phantomjs and make it easy to use in scale fashion.

**Comment by anirudhkkw** [comment]
Hi,

```
request(URL, function(error, response, data) {
    
    conversion({ 
   html: data, 
   fitToPage: true,
   viewportSize: {
        width: 640
    },
    format: {
        quality: 100
    },
    paperSize: {
      margin: "0cm"
    },
   phantomPath: require("phantomjs-prebuilt").path
 }, function (err, data){
  res.setHeader('Content-type', 'application/pdf');
  data.stream.pipe(res);
 })
});
```

I tried doing this. First request the url and get the HTML and then pass HTML to the PDF generator but to no avail. Am I doing something wrong?

**Comment by pofider** [comment]
> but to no avail
What do you mean?

The code looks fine. You will likely not get css and js applied because of relative links, but you get at lease more idea if the problem is with particular page css and js or it is a server font issue.

**Comment by anirudhkkw** [comment]
I meant that the blue tinge at the end of the pdf is still present.

**Comment by pofider** [comment]
Ah ok, the blue part is there also with a "Hello world" html right? There is likely something wrong with your ubuntu packages, unfortunately I've no clue how to trouble shoot it. Just to make sure, I've tried the following code on ubuntu 16.04 and I've no blue part there

```js
var conversion = require('phantom-html-to-pdf')()

conversion({ 
   html: 'hello',
   fitToPage: true,
   viewportSize: {
        width: 640
    },
    format: {
        quality: 100
    },
    paperSize: {
        margin: "0cm"
    },
   phantomPath: require("phantomjs-prebuilt").path
 }, function (err, data){
    data.stream.pipe(require('fs').createWriteStream('out.pdf'));
 })
```

**Comment by anirudhkkw** [comment]
so sorry. The body in html code had a different background color :P my bad :P
