### ISSUE TITLE
Possibility to inject scripts

### ISSUE THREAD

**Issue by Mardaneus86** [pofider/phantom-html-to-pdf#45]
PhantomJS allows for the possibility to inject JS files into the page. I couldn't find this functionality here. If it fits the roadmap I could submit a PR, but I don't have a good solution on how to unit test this.

The edit is contained in the `lib/scripts/conversionScriptPart.js`:

Adding these lines to the `page.onInitialized` function
```js
    if (body.injectScripts && body.injectScripts.length > 0) {
      body.injectScripts.forEach(function(script) {
        page.injectJs(script);
      });
    }
```

This functionality could then be triggered by calling `conversion` like this:
```js
conversion({
    url: "http://example.com",
    injectScripts: [
      __dirname + '/polyfill.js' // <-- include the full path to the script(s) to be injected
    ],
    waitForJS: true
  }, function(err, pdf) {
    ...
  })
```

Thoughts?

**Comment by pofider** [comment]
Yes, this makes sense. It would be great if you can make a PR with this.

You can also easily unit test it. Just link `injectSript` with `console.log('test')` content and make sure the `test` string is contained in the conversion response log `res.logs[?].should.containEql('test')`.
