### ISSUE TITLE
Converted pdf texts are not showing clearly 

### ISSUE THREAD

**Issue by SantoshSKhavekar** [pofider/phantom-html-to-pdf#51]
Hi ,

I am using this module to convert html string to PDF file in node.js like this,

```js
var htmlstr="<h1>Test</h1><p>Hello world</p>";
var conversion = require("phantom-html-to-pdf")();
conversion({ html: htmlstr}, function(err, pdf) {
  console.log(pdf.logs);
  console.log(pdf.numberOfPages);  
  pdf.stream.pipe(fs.createWriteStream(__dirname+'/destination.pdf'));   
});
```
after that I viewed pdf file ,in that the text is not showing .

**Comment by pofider** [comment]
You may be missing some packages required by phantomjs. Please check troubleshooting installation section

https://github.com/pofider/phantom-html-to-pdf#installation-troubleshooting

**Comment by SantoshSKhavekar** [comment]
Yes I missed out.Now It is working like charm after doing these two installation  "urw-fonts" and "fontconfig".
Thank you guys.....
