### ISSUE TITLE
Generate pdf/A documents ?

### ISSUE THREAD

**Issue by jmcollin78** [pofider/phantom-html-to-pdf#52]
Hi there,

For Document Management System (DMS), we need to get some PDF/A documents to be generated. Cf. https://fr.wikipedia.org/wiki/PDF/A-1
Is there any plan to support this format ?

Many thanks for your response.

**Comment by pofider** [comment]
Hi,

this is just wrapper around phantomjs package and I'm afraid that it doesn't support different formats of pdf.

**Comment by pofider** [comment]
Closing as this is not a concern of this package.
