### ISSUE TITLE
dynamic Header/ footer 

### ISSUE THREAD

**Issue by rich25200** [pofider/phantom-html-to-pdf#60]
Hi,

I would like create a dynamic header and footer for the last page. It is possible? 

I saw that I just can create the same header and footer with local options.

Thanks

**Comment by pofider** [comment]
You can try to hide the header with javascript for the last page, however you cannot change the size for example.

Check the example here
https://jsreport.net/learn/phantom-pdf#page-numbers

**Comment by rich25200** [comment]
How I can know if I am on the last page?

**Comment by pofider** [comment]
Just extend the linked example and use "{#pageNum} === {#numPages}"
