### ISSUE TITLE
knowing when the PDF has finished to generate

### ISSUE THREAD

**Issue by rich25200** [pofider/phantom-html-to-pdf#61]
Hi,

I have a file system watcher that watch a folder. When a file is detected, I read the file and I convert it into PDF with phantom-html-to-pdf.

My concern is when too many files is handled, Phantomsjs crashs. 

I would like tell at phantomjs to  manage a maximum 20 files for exemple. Is it possible?

Or would you advise me how I can make this without this error?

Thanks

**Comment by bjrmatos** [comment]
hi @rich25200 , if you are experimenting problems with the maximum amount of files that phantomjs can process just implement a basic limit in your code:

```js
// pseudo-code
var currentFilesProcessing = 0;
var MAX_CONCURRENT_FILES = 5;
var pendingFiles = [];

dir.on('watch', function (file) {
  pendingFiles.push(file);
});

setInterval(function () {
  if (currentFilesProcessing >= MAX_CONCURRENT_FILES || pendingFiles.length === 0) {
    return;
  }
  
  currentFilesProcessing++;

  startConversion(pendingFiles.shift(), function () {
    currentFilesProcessing--;
  });
}, 3000);

function startConversion(file, cb) {
  // ..use phantom-html-to-pdf here..
}
```

i'm afraid i can't help you more here, i'm going to close the issue since this is not a problem related with the library.
