### ISSUE TITLE
Is numberOfWorkers implemented?

### ISSUE THREAD

**Issue by timruffles** [pofider/phantom-html-to-pdf#62]
I'm a bit confused that I can't see [`numberOfWorkers`](https://github.com/pofider/phantom-html-to-pdf/search?utf8=%E2%9C%93&q=numberOfWorkers&type=) anywhere in the codebase aside from the README and a place where it's assigned to an options object. It seems unused.

It's also not in [PhantomJS](https://www.google.co.uk/search?hl=en&q=site%3Aphantomjs.org%2F+numberOfWorkers&oq=site%3Aphantomjs.org%2F+numberOfWorkers&gs_l=serp.3...48197.48347.0.48806.2.2.0.0.0.0.396.396.3-1.1.0....0...1.1.64.serp..1.0.0.PnpsNihf66g) itself.

I'm sure I'm missing something :) If it isn't doing anything this project doesn't seem to match the README (e.g re options nor FIFO?).

**Comment by timruffles** [comment]
My bad - found out that it's passed down into phantom-workers.

**Comment by bjrmatos** [comment]
i was about to replied you, haha glad that you found it!
