### ISSUE TITLE
image (png/jpg) not rendered in pdf

### ISSUE THREAD

**Issue by david-rouchet** [pofider/phantom-html-to-pdf#63]
The generated pdf does not render the images that are in the html, although the temporary generated html file does display them properly. Is there a special settings or method to have them in the pdf?

**Comment by pofider** [comment]
It should work, but again, this package is just a wrapper around phantomjs and you need to search for your rendering issues there
https://github.com/ariya/phantomjs

**Comment by pofider** [comment]
If you reference local image with file protocol, you need to set the `allowLocalFilesAccess:true` option
https://github.com/pofider/phantom-html-to-pdf#local-options

**Comment by david-rouchet** [comment]
@pofider Tnx for the feedback. I did that too (the option) but with no more success.
