### ISSUE TITLE
Link are not working

### ISSUE THREAD

**Issue by david-rouchet** [pofider/phantom-html-to-pdf#64]
The links referencing other part of the page (ex: <li><a href='#home'>Home</a></li> in the html before pdf conversion) are not working in the pdf document. Clicking on those links on the pdf ask to open a new file which does not work either, instead of pointing at the right location within the current pdf file. Any idea, solutions?

**Comment by pofider** [comment]
This package is just a wrapper around the phantomjs which is in fact doing the pdf rendering.
You should take a look there https://github.com/ariya/phantomjs

Btw it doesn't support anchors in the version 1, see how to use the latest here
https://github.com/pofider/phantom-html-to-pdf#phantomjs2
