### ISSUE TITLE
Print pdf with node

### ISSUE THREAD

**Issue by lumenier1** [pofider/phantom-html-to-pdf#67]
Hi, sorry for stupid question, but how to:
1) send converted pdf file to printing query via nodejs script? (not by `window.PHANTOM_HTML_TO_PDF_READY = true;` in html script tag)
2) save converted pdf document on the local file system by node? :)
There is no docs about it, it's a pity.

**Comment by lumenier1** [comment]
NodePDF solved my problem.

**Comment by pofider** [comment]
Closing. Try general development forums instead.
