### ISSUE TITLE
body.setting.resourceTimeout causing ajax and script references error

### ISSUE THREAD

**Issue by walter-psjr** [pofider/phantom-html-to-pdf#7]
At times, script references are not loaded and ajax requests return http
status 0 with body.settings.resourceTimeout 1000.

The idea is that this timeout is configurable?

https://github.com/walter-psjr/phantom-html-to-pdf/commit/7dde10d6204d015d8260a771a305fac9c4082f13

**Comment by bjrmatos** [comment]
the resource timeout is already configurable

```js
var conversion = require("phantom-html-to-pdf")();

conversion({  
  // other options...
  settings: {
    resourceTimeout : 180000
  }
// other options..
}, function(err, pdf) {
});
```
