### ISSUE TITLE
No text on mac

### ISSUE THREAD

**Issue by jamesAtcodeninja** [pofider/phantom-html-to-pdf#71]
I've installed and used the package as noted for macs - phantomjs-prebuilt. 
But the rendered pdf file does not have any text on it. Can you please advise what to do in this situation?

**Comment by bjrmatos** [comment]
can you share more details? for example exact version of macOS, your node.js version. can you also share the code that you are using to test? does any logs get printed in the console when you run your application? if there are logs please post them here too.

**Comment by jamesAtcodeninja** [comment]
Using your advice I looked into the logs and realized relative urls were not working. I was able to fix it afterwards, thanks.
