### ISSUE TITLE
waitForJS getting timeout

### ISSUE THREAD

**Issue by rathorer** [pofider/phantom-html-to-pdf#72]
Hi, 
I am not sure if I am doing something wrong, but I have already spent 2 days on it, and with waitForJS and waitForJSVarName I am unable to create Pdf, every time I tried to create pdf, it throws "timeout error" irrespective of whatever timeout value I put in settings. And I don't see any error or a message to indicate what went wrong.
```
const converter = require("phantom-html-to-pdf")({
    numberOfWorkers: 2,
    timeout: 18000, //18 sec
    portLeftBoundary: 1000,
    portRightBoundary: 4000,
    host: '127.0.0.1',
    phantomPath: "..\\myapp\\node_modules\\phantomjs\\lib\\phantom\\phantomjs.exe",
    maxLogEntrySize: 1000
});
var createPdf = function (htmlUrl, createHere, token) {
            converter({
                url: htmlUrl,
                footer: '<div style="text-align:center">{#pageNum}/{#numPages}</div>',
                injectJs:[Path.join(__dirname, '../public/bower_components/jquery/dist/jquery.min.js'),
                     Path.join(__dirname, '../public/dynamic-documents/thePageJS.js')],
                waitForJS: true,
                waitForJSVarName: "htmlReadyToBePrinted",
                settings: {e
                    javascriptEnabled: true
                },
                customHeaders: [{ Authorization: 'Bearer ' + token }],
                format: {
                    quality: 100
                }
            }, function (err, pdf) {
                if (err) {
                    console.error('Error while printing pdf.', err);
                    return;
                }
                console.log(pdf.logs);
                console.log(pdf.numberOfPages);
                var filePath = fs.createWriteStream(createHere);
                pdf.stream.pipe(filePath);
            });
```
I cross verified the paths of JS, all looks correct.
In my thePageJS.js, all I am doing making a API call and upon getting response (error or success), setting the window.htmlReadyToBePrinted to 'true'.

This is what the error I get everytime:
```
Error while printing pdf. { Error: Timeout
    at c:\CDN\MyApps\node_modules\phantom-workers\lib\phantomManager.js:117:29
    at c:\CDN\MyApps\node_modules\phantom-workers\lib\phantomWorker.js:120:13
    at c:\CDN\MyApps\node_modules\phantom-workers\lib\phantomWorker.js:136:20
    at Socket.<anonymous> (c:\CDN\MyApps\node_modules\phantom-workers\lib\checkPortStatus.js:45:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12) weak: true, message: 'Timeout', phantomTimeout: true }
```

**Comment by bjrmatos** [comment]
@rathorer hi! can you please prepare a repository with all the code needed to test your problem? we have limited time and the best (and faster) will be to provide a way to reproduce your problem.

Another reason to ask you for a repository is that there are other files referenced in your example which we don't know its contents, so we won't be able to fully check what is happening). Thanks.

**Comment by rathorer** [comment]
@bjrmatos I have created a example repository (hope its helpful for others). 
[phantom-html-to-pdf-example](https://github.com/rathorer/phantom-html-to-pdf-example)
As of now in the above example waitForJS is disabled and pdf gets generated without any issues, however if you change it to make it enable, its always ending up in timeout.
So as of now to simulate my webapi i just kept the setTimeout, for which also its failing. So I am not able to populate my pdf with dynamic data.

**Comment by bjrmatos** [comment]
@rathorer if you don't activate `waitForJS` and [check your console](https://github.com/rathorer/phantom-html-to-pdf-example/blob/master/pdfGenerator.js#L54) you will see some errors:

<img width="977" alt="captura de pantalla 2017-08-02 a las 11 05 02 a m" src="https://user-images.githubusercontent.com/4262050/28882961-75e7520a-7772-11e7-9cc8-c2a634824582.png">

the most important is the `SyntaxError: Parse error` error.. which means that phantomjs is having trouble to understand the javascript in your page, more specifically [you are using ES6 (const declarations)](https://github.com/rathorer/phantom-html-to-pdf-example/blob/master/agreement.html#L24) in your page which phantomjs does not understand, as the first step to fix your problem just make sure the javascript of your page is ES5 compatible, then check for the other errors.

**Comment by rathorer** [comment]
Hey @bjrmatos , this is helpful, thanks a lot, I was able to fix the example by removing all ES6 related code, I think I should be able to fix my original code as well.

**Comment by ndaiya** [comment]
@bjrmatos I am passing URL as parameter rather then the html which has lot of angular code written to it and seems like each time I am getting the timeout error. Note : I have very large amount of data its taking upto 1 minutes to load the view if we are using chrome. But not sure what to set for the timeout.

**Comment by bjrmatos** [comment]
@ndaiya the default timeout is 180s so if your page load before that, it should be ok. maybe there is some new javascript syntax in your page that phantomjs does not recognize, phantomjs only recognize ES5, maybe you can verify that. or maybe you are not applying the [`waitForJS` signal](https://github.com/pofider/phantom-html-to-pdf#programmatic-pdf-printing) correctly in your js code. you can verify that by removing some code in your page, and use the `waitForJS` signal with some simple code, if it works, then maybe you are not calling `window.PHANTOM_HTML_TO_PDF_READY = true` in the way that you expect.

**Comment by ndaiya** [comment]
@bjrmatos Tried with window.PHANTOM_HTML_TO_PDF_READY = true, with the timeout for testing purpose it worked but its generating empty pdf. 
What I am seeing  in my logs is : 
`[ { timestamp: 2017-11-24T06:23:23.592Z,
    message: 'Converting in http server based phantomjs 2.1.1',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.594Z,
    message: 'Request http://localhost:9000/shared/e6d0e199-6182-4f89-97b4-ab5527fe4c52',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.625Z,
    message: 'Request http://localhost:9000/app/vendor.css?691d4b1b41983464e407',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.625Z,
    message: 'Request http://localhost:9000/app/appRun.css?691d4b1b41983464e407',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.626Z,
    message: 'Request http://www.gstatic.com/cv/js/sender/v1/cast_sender.js',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.626Z,
    message: 'Request http://localhost:9000/socket.io/socket.io.js',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.626Z,
    message: 'Request http://localhost:9000/app/vendor.bundle.js?691d4b1b41983464e407',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.627Z,
    message: 'Request http://localhost:9000/app/appRun.js?691d4b1b41983464e407',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:23.628Z,
    message: 'Request http://localhost:35729/livereload.js?snipver=1',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:26.970Z,
    message: 'Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.',
    level: 'warn' },
  { timestamp: 2017-11-24T06:23:26.970Z,
    message: '    : 35',
    level: 'warn' },
  { timestamp: 2017-11-24T06:23:26.971Z,
    message: 'Warning: DebounceInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you\'re not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.',
    level: 'warn' },
  { timestamp: 2017-11-24T06:23:26.971Z,
    message: '    : 35',
    level: 'warn' },
  { timestamp: 2017-11-24T06:23:27.474Z,
    message: 'Request http://localhost:9000/api/poll/currentTime',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:27.489Z,
    message: 'Request http://localhost:9000/api/la-telemetry/page-visit',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:27.498Z,
    message: 'Time initialized at - Start: Fri Nov 24 2017 10:50:00 GMT+0530 (IST) End: Fri Nov 24 2017 11:50:00 GMT+0530 (IST)  ',
    level: 'debug' },
  { timestamp: 2017-11-24T06:23:27.535Z,
    message: 'Unable to load resource (#10URL:http://localhost:9000/api/la-telemetry/page-visit)',
    level: 'warn' },
  { timestamp: 2017-11-24T06:23:27.535Z,
    message: 'Error code: 204. Description: Host requires authentication',
    level: 'warn' } ]`
But I am pretty sure its been working without authentication. As this page doesn't need authorization.

**Comment by bjrmatos** [comment]
> Tried with window.PHANTOM_HTML_TO_PDF_READY = true, with the timeout for testing purpose it worked but its generating empty pdf.

@ndaiya  just to be sure.. have you activated that `waitForJS` option too? (like the example)

<img width="269" alt="captura de pantalla 2017-11-24 a las 9 58 32 a m" src="https://user-images.githubusercontent.com/4262050/33215522-30028c42-d0fe-11e7-8737-06dbb2b3c3ef.png">

seems like you've not activated the `waitForJS` or maybe you are calling `window.PHANTOM_HTML_TO_PDF_READY = true` too early or late in your code.

> But I am pretty sure its been working without authentication. As this page is shared.

i don't have more advice here, this seems more like a problem with your other pages, so i can't tell you what is wrong here.

**Comment by ndaiya** [comment]
@bjrmatos If I am enabling the waitForJs, each time it ends with the response : 
{"weak":true,"message":"Timeout","phantomTimeout":true}
And if not setting then it works but results in empty pdf.

**Comment by bjrmatos** [comment]
> If I am enabling the waitForJs, each time it ends with the response :
> {"weak":true,"message":"Timeout","phantomTimeout":true}
> And if not setting then it works but results in empty pdf.

yes, it seems like you are not calling `window.PHANTOM_HTML_TO_PDF_READY = true` at the right moment in your app or maybe you are calling it in an event that it is never emitted or emitted too early. unfortunately i can't give you more insight without running code, if you can post here the content of the external url (html with angular app), i can take a look quickly if it is not too complex.
