### ISSUE TITLE
How do I generate .pdf file using this?

### ISSUE THREAD

**Issue by ishwarrimal** [pofider/phantom-html-to-pdf#73]
There is not much description on generating .pdf file from html. 
I was using html-pdf where i could provide the name of the file that i want to generate and other stuff. 
I am quite lost in this. Please help me out.

**Comment by pofider** [comment]
```js
var conversion = require("phantom-html-to-pdf")();
conversion({ html: "<h1>Hello World</h1>" }, function(err, pdf) {
  console.log(pdf.logs);
  console.log(pdf.numberOfPages);
  pdf.stream.pipe(res);
});
```

The package offers stream in callback, save it to file with name of your wish.

**Comment by ishwarrimal** [comment]
Okay, i tried this. I am getting following error:
'res is not defined'
Am i suppose to give file name instead of res or?
If possible can you please show me with example on how to do this?
