### ISSUE TITLE
Need more thorough examples, thanks

### ISSUE THREAD

**Issue by atljoseph** [pofider/phantom-html-to-pdf#77]
Can't get injectJs to work.

**Comment by atljoseph** [comment]
got it to work, thanks, HOWEVER I observed no failure message when the file was unavailable or the wrong path was provided.  Is this silent failure by design? Thanks

**Comment by bjrmatos** [comment]
> HOWEVER I observed no failure message when the file was unavailable or the wrong path was provided. Is this silent failure by design? Thanks @

hi! which file path are you referring to? can you point the name of the option or the part of code where it silently fails if you pass the wrong path?
