### ISSUE TITLE
Can you create dynamic headers/footers (i.e. use html/javacript/css) with phantom-html-to-pdf

### ISSUE THREAD

**Issue by nathan-martinez** [pofider/phantom-html-to-pdf#8]
I'm trying to create a report that has the current date and time and displays some names provided in the data.

**Comment by pofider** [comment]
The content of header/footer can contain html,css and javascript. So yes.

**Comment by nathan-martinez** [comment]
Thank you! Can you reference the data?

**Comment by pofider** [comment]
What kind of data? I am missing a context here....

**Comment by nathan-martinez** [comment]
Sorrr; the JSON data that is passed to the api to generate the report.

**Comment by pofider** [comment]
jsreport seems to be the context here. Yes, you can use templating engines or even child templateds in header/footer.

**Comment by nathan-martinez** [comment]
Thanks again! You've built an amazing tool.
