### ISSUE TITLE
workers

### ISSUE THREAD

**Issue by stellanhaglund** [pofider/phantom-html-to-pdf#83]
Hi I'm noticing that the first generation of an pdf when a server is started is a lot slower then the rest.

I have set `numberOfWorkers` to `2, does that start the workers directly or will the workers not start until there is an conversion?
Or is there any other way of starting workers so that they are running when the first request comes?

**Comment by bjrmatos** [comment]
> I have set numberOfWorkers to `2, does that start the workers directly or will the workers not start until there is an conversion?

they start when the first conversion comes.

> Or is there any other way of starting workers so that they are running when the first request comes?

right now, there is no way to start the workers directly without triggering a conversion, it can be a nice addition.

for now you can run an empty conversion right when you create the phantom-html-to-pdf instance if you want to have the workers ready before your first request comes.

**Comment by pofider** [comment]
I've updated readme to include warmup section.

I believe that running empty conversion is obvious solution. I don't plan to implement an automatic "warm up". If someone wants to give it some time and implement it, I will gladly merge the PR thought.
