### ISSUE TITLE
Security Issue: Upgrade dependency phantomJs to latest version v2.1.16

### ISSUE THREAD

**Issue by kamesh95** [pofider/phantom-html-to-pdf#86]
Phantomjs module is dependent on request module which in turn is dependent on the hawk module. Hawk module had denial of service vulnerability with its earlier versions. Now, request module uses the latest hawk module and phantomjs also uses the updated request module in which this issue with hawk is resolved now. So please update the phantomJs module to v2.1.16 

Link to hawk vulnerability - https://nodesecurity.io/advisories/77

**Comment by pofider** [comment]
Thank you for notice. However...

See https://github.com/pofider/phantom-html-to-pdf/issues/39 why we don't update to the phantomjs 2 now.

See here how you can use the latest phantomjs with this package if you want.
https://github.com/pofider/phantom-html-to-pdf#phantomjs2
