### ISSUE TITLE
Change font type

### ISSUE THREAD

**Issue by NTurchi** [pofider/phantom-html-to-pdf#88]
Hi,
Actually, when i generate PDF with your library i get trueType (CID) Font type in my document (See image below) but i don't want this kind of font type.
How i can change this behaviour ?

Thanks for your help

![image](https://user-images.githubusercontent.com/16674693/36036017-fd1b997a-0db8-11e8-9516-a7bb510fb15b.png)

**Comment by pofider** [comment]
This library is just a wrapper around phantomjs.
Please try to check phantomjs issues directly.
https://github.com/ariya/phantomjs
