### ISSUE TITLE
Problem with CSS being applied?

### ISSUE THREAD

**Issue by Jordan4jc** [pofider/phantom-html-to-pdf#89]
It seems when this gets created as a PDF some of the CSS I've set in a `style` at in the page head isn't being applied.

One thing that's happening is I have some elements rendered on the page and I set their width and height to hard inch values but when the PDF comes through to the page they are rendering much larger than that on their pages.

Is there something I need to know about how CSS is rendered?

**Comment by pofider** [comment]
This package is just a wrapper around phantomjs.
It manages how many phantomjs are being used for printing, but the printing it self is done by phantomjs.

I recommend to search [phantomjs repisotory](https://github.com/ariya/phantomjs) for the solution.
