### ISSUE TITLE
Breaks when setting numberOfWorkers without setting strategy to 'dedicated-process'

### ISSUE THREAD

**Issue by PaddyMann** [pofider/phantom-html-to-pdf#9]
Love the concept of this module - exactly what we needed :)

Have just overcome an issue:
- I tested without multiple workers: No problem
- I set `numberOfWorkers: 6`, and hit the error pasted in below
- I was able to fix by setting the `strategy: 'dedicated-process'`

Might be a documentation issue?

Would also love some guidance on how many workers a standalone server with X GB of RAM can handle...

**Comment by PaddyMann** [comment]
I spotted your comment that `dedicated-process` can address some issues with corporate proxy... I had ignored this as I'm just testing locally on a Mac at the moment.

**Comment by pofider** [comment]
`dedicated-process` strategy spins up one phantom process for each pdf printing. It currently doesn't use `numberOfWorkers` property.

What is the error you get? I am not getting an error with 6 workers.s.

**Comment by PaddyMann** [comment]
With it the `dedicated-process` strategy commented out, I get the following error:

`{ [Error: Timeout] weak: true, message: 'Timeout' }`

**Comment by pofider** [comment]
Unfortunately I somehow ignored/forget this. Looking at it now seems to me that the rendering regularly timedout if there was too many resources used by 6 workers. 

I'm cleaning issues now. If you have still problems and want to inquiry them, please reopen or create a new issue.
