### ISSUE TITLE
Error: spawn EACCES 

### ISSUE THREAD

**Issue by maghidini** [pofider/phantom-html-to-pdf#92]
Using a node app, in Mac OS, with phantom 2.
Both strategies, dedicated-process and phantom-server, gives me an Error: spawn EACCES  doing childProcess.execFile

**Comment by pofider** [comment]
What if you run phantomjs executable from the command line?

**Comment by maghidini** [comment]
@pofider is working. I running on `/Users/maghidini/project/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs`

BTW I got it also as a cli that's why the `npm install` drop me this:

> phantomjs-prebuilt@2.1.12 install /Users/maghidini/project/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt
> node install.js

**Comment by pofider** [comment]
Hm. It looks like some kind of permission issues.
I don't think it is problem of this package. We just spin multiple phantomjs instances, nothing more here.

**Comment by maghidini** [comment]
@pofider yes, it weird. I ran it with sudo, also chmod the whole project to 777, and no luck so far. BTW I'm using it from `jsreport-phantom-image`. Doing it with `jsreport-phantom-pdf` works, but image doesn't :(

**Comment by bjrmatos** [comment]
i'm closing this in favor of jsreport/jsreport-phantom-image#5 to avoid duplications.
